# Demanda

## O que é {-}

- É uma manifestação de necessidades desencadeada por fenômenos associados. Esta por sua vez provoca e estimula o processo de melhoria contínua. Por exemplo: O fenômeno envelhecimento da população, desencadeia necessidades de mudanças no sistemas previdenciários, educacional e de saúde em um país. Esta necessidade por sua, vez provoca e estimula o processo de melhoria contínua desses sistemas transformando um possível colapso no futuro em oportunidades.

- Geralmente é apresentada como um resumo de várias conversas, consultas e análises com envolvidos no mesmo tema ou interesse.

- Habilidade do ser humano e de grande valor para a sociedade.

- Tende a permitir a interpretação nos dois sentidos por exemplo se tenho uma solução já existente, ela existe pra cumprir qual demanada? ou se eu tenho uma determinanda demanda, que tipo de solução poderia atendê-la?.


## Qual o objetivo {-}

- Estimular a interação entre a mente, o ambiente e as coisas existentes, possibilitando a criação de novas coisas.

- Auxiliar no desenvolvimento e evolução das sociedades.


## De onde vem {-}

- Competição acirrada em determinados mercados (e.g. tecnologia)

- Escasses de recursos que tende a exigir que melhor aproveitamento (e.g.alimentos)

- Comportamento da opinião pública (e.g. reação ao ver altos índices de doenças, envelhecimento da população, acidêntes de trânsito, fenômenos climáticos)

- Desenvolvimento acelerado de países emergentes(e.g. infraestrutura, serviços médicos etc)

- Interação entre as pessoas (e.g. feiras, eventos, práticas de comércio entre países)

- O ambiente, é um fator importante  na geração de demanda mas não será discutido nesse livro, no entanto deixo para a reflexão do leitor questionar-se que fatores ambientais foram importantes para que a Mesopotamia-Iraque(3500AC), Egito(331AC), Grécia(444AC), Roma(117), Florença(1350) e Holanda(1600) atraissem e concentrassem um número expressivo de mentes brilhantes, boas ideias e inovações que posteriormente foram usadas no mundo todo?

## Como fazer {-}

- Ação de visionário implementador

- Ação de comunicação e educação


## Pra onde vai {-}

- Geralmente para equipe multidisciplinar que fará a análise do fenômeno, identificação do problema, definição dos objetivos e metricas de sucesso


## Qual o resultado {-}

- Formação de pull de ideias 
- Fomenta e suporta as equipes de melhoria contínua
- Apresenta bases para que outras ideias surjam
