# Definição do problema, objetivo e metrica de sucesso

## O que é {-}

- Interpretação das demandas, diagnóstico de causa raiz, proposição de solução eficaz associado a uma métrica para avalição.

- Etapa crítica no melhoria contínua exige trabalho em equipe preferencialente multidisciplinar porêm com apenas um foco, o problema.

- Transformação dos resultados de análise dos fenômenos sob diversos pontos de vista em objetivos claros e bem definidos. Por exemplo: Imagine um paciênte com febre e dor de cabeça. Uma ação paliativa seria dar um remédio para dor de cabeça, mas uma análise de hemograma pode identificar que a dor de cabeça e febre são sintomas reativos do corpo que está sob ataque de uma bactéria gran positiva, a febre aumenta a temperatura que estimula os neutrófilos grudados nas paredas das artérias a cair na circulação para atacar o foco infeccioso. Estas análises ajudam na proposição de ações eficazes.

## Qual o objetivo {-}

- Permitir que ações eficazes sejam tomadas

- Evitar agravamento do problema causado por ações paliativas

- O trabalho em equipe multidisciplinar com foco no problema pode oferecer uma visão sistemica o que pode ser muito valioso.Vamos para um exemplo de necessidade de visão sistemica. 

Imagine que sou um consultor empresarial e fixo metas para cada setor. Um deles, o de compras de caixas, para bater sua meta opta pelo modelo de lote economico de compra baseado em preço onde se compra grandes volumes com preços menores e fornecedores diversos. Como as caixas vem de vários fornecedores, elas possuem variações de tamanho, espessura e angulo. Ao colocar as caixas na montadora automática de caixas, a variação provoca desgaste excessivo de ventosas acabando com o estoque da peça e fazendo a maquina parar. A parada da maquina atraza da produção que aloca mão de obra para outros atividades prejudicando drasticamente a produtivdade global.


## De onde vem {-}

- Da necessidade de se beneficiar dos eventos e mudanças em curso ao invés de ser surpreendidos por eles

## Como fazer {-}

- O PDCA e ferramentas da qualidade são meios bastante uteis, ou pelo menos o diagrama ishikawa e o método dos 5 porquês.

```{r, diagrama-ishikawa,   results=  FALSE,  fig.align='center',fig.width = 8, fig.height = 4}

#pacotes usados
library(tidyverse)
library(qcc)

#criando o diagrama de ishikawa
cause.and.effect(cause = list(Medida   = c("Aferição","Acompanhamento","Indicador"),
                              Material = c("Qualidade","Padronização","Entrega"),
                              Pessoas  = c("Comunicação","Disciplina","Criatividade"),
                              Ambiente = c("Calor","Frio","Espaço"),
                              Metodo   = c("Procedimento","Etapas","Manuais"),
                              Maquina  = c("Equipamento","Ferramenta","Instrumentos")),
                 effect = c("Redução \n no Nº de \n defeitos"),
                 title = "Diagrama de causa e efeitos",
                 cex = c(1,.8,.8),
                 font = c(2,1,1))


```



## Pra onde vai {-}

- Com os objetivos e métricas de sucesso bem definidos e claros, o próximo passo é a ação.

## Qual o resultado {-}

- Clareza nas ações em busca da melhoria contínua

- Transparência nos resultados, uma vez que as métricas de sucesso foram bem definidas